public enum Property { 
    Critical = 0, 
    Resiliense = 1, 
    Attack = 2, 
    PowerAttack = 3, 
    Evasion = 4, 
    PowerDefense = 5,
    SpiritPoints = 6, 
    Life = 7, 
    ValiantPoints = 8, 
    Protection = 9, 
    Fortitude = 10, 
    AttackDamage = 11, 
    PowerDamage = 12, 
    AttackSpeed = 13, 
    CastingSpeed = 14, 
    CriticalDamage = 15, 
    ArmorPenetration = 16, 
    Reaction = 17, 
    Counter = 18, 
    Threat = 19 
};